# Generated by Django 6.0 on 2025-12-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_product_harvest_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='harvest_time',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='planting_time',
            field=models.CharField(max_length=200),
        ),
    ]
